baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[markup.goldmark.renderer]
  unsafe = true

[caches]
  [caches.images]
     dir = ':cacheDir/images'
